### PR TITLE
Add Confirmation Dialogs for Gold Selection Actions

### LINKED ISSUE #23: Option to remove golds
In case of accidental addition of the wrong gold or a change in what the user decides they want to be gold, it would be cool if there were an option to select golds and remove them as the user saw fit.

### PR DESCRIPTION
**Pull request by AsH1605**
### Description
This PR addresses [Option to remove golds #23] by introducing confirmation dialog boxes to improve the user experience during gold management actions. These dialogs ensure users can confirm or cancel their actions, preventing accidental modifications.

**Closes #23**

### Changes Made
1. Added dialog boxes to the following functions:
   - `btn_gold_replace()`  
   - `btn_gold_add()`  
   - `btn_gold_manual()`  

2. Each dialog box prompts the user with a confirmation message. If the user cancels, the operation is aborted.

### Code Example
```javascript
function btn_gold_replace() {
    if (confirm("Are you sure you want to save the changes?")) {
        // Post
    } else {
        // Cancel operation
        return;
    }
}

function btn_gold_add() {
    if (confirm("Are you sure you want to save the changes?")) {
        // Post
    } else {
        // Cancel operation
        return;
    }
}

function btn_gold_manual() {
    if (confirm("Are you sure you want to save the changes?")) {
        // Post
    } else {
        // Cancel operation
        return;
    }
}

### CODE REVIEW

**Comment by unhammer** [comment]
This puts in a confirmation question when adding golds, but doesn't actually close #23 which asks for a way to _remove_ golds (perhaps weeks after they've been added!). 

I'm not sure I would want a confirm dialog when adding, I'd prefer to just hit enter and then it's added – but also to be able to remove it quickly if I change my mind. It's a bit more work to get that delete function implemented (but would be useful).

**Comment by TinoDidriksen** [comment]
We do not want confirmation dialogs - it's all under version control, which is sufficient confirmation and safeguard.

So, try again. We need a new modal that allows for managing existing golds.

**Comment by AsH1605** [comment]
Since there could be around 1000 golds, how would you like them to be displayed in the UI? Would you prefer a way to:

- Display all golds at once?
- Use pagination or infinite scrolling to make navigation easier?
- Have a search/filter option to quickly find specific golds?

Also, should the delete function be accessible immediately via a delete button next to each gold, or would you prefer an additional confirmation step for deletion?

**Comment by TinoDidriksen** [comment]
Each input should be edited separately. There will likely not be more than 5 golds for each input. The modal should allow for adding/editing/deleting golds.

**Comment by AsH1605** [comment]
Understood. I will try to implement it and make the necessary changes.

**Pull request closed without merging**
